#!/bin/sh

# git
alias gaa="git add . && git status"
alias gb="git branch -v"
alias gs="git status"

# color
alias diff="diff --color"
alias grep="grep --color"
alias l="ls -ahl --color"
alias la="ls -ah --color"
alias ll="ls -hl --color"
alias ls="ls --color"

# confirm before overwriting something
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -iv"

# programs
alias v="nvim"
