#!/bin/sh

# set displays
setdisplays

# faster key delay and rate
xset r rate 210 40

# start compositor
picom -b

# start notification daemon
dunst &

# start screenshot program
flameshot &

# start window manager
exec bspwm
