#!/bin/sh

# set displays
set-displays

# set screen brightness
xrandr --output eDP-1 --brightness 0.8

# faster key delay and rate
xset r rate 210 40

# start compositor
picom -b --config "$XDG_CONFIG_HOME/picom/picom.conf"
