#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

NUM_DISPLAYS=$(xrandr -q | awk '/ connected/ {print $1}' | wc -l)
if [ "$NUM_DISPLAYS" == 1 ]; then
  bspc monitor eDP-1 -d 1 2 3
  bspc monitor DP-3 -r
elif [ "$NUM_DISPLAYS" == 2 ]; then
  bspc monitor eDP-1 -d 3 4
  bspc monitor DP-3 -d 1 2
fi

bspc config border_width 0
bspc config window_gap 15
bspc config ignore_ewmh_fullscreen all

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true

bspc rule -a Sxiv state=floating
bspc rule -a Zathura state=tiled

$HOME/.config/polybar/launch
