#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 I II III
bspc monitor DP-3 I II III

bspc config border_width         1
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch
