#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d I II
bspc monitor DP-3 -d III IV

bspc config border_width 1
bspc config window_gap 30

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch
