#!/bin/sh

# terminate already running bar instances
killall -q polybar

# launch Polybar, using default config location ~/.config/polybar/config.ini
polybar top 2>&1 | tee -a /tmp/polybar.log & disown
