#!/bin/sh

OPTION=$(printf "full\\nscreen\\nselect" | rofi -dmenu -i -p "Select screenshot style")
case "$OPTION" in
  full) flameshot full;;
  screen) flameshot screen -n 1;;
  select) flameshot gui;;
esac
